### ISSUE TITLE
Error building svelte

### ISSUE THREAD

**Issue by hammady** [hammady/wwpray#3]
When invoking the function locally, I get this:

```
> wwpray-frontend@0.0.1 build
> vite build


vite v4.4.11 building SSR bundle for production...
✓ 73 modules transformed.
✓ built in 540ms
Could not resolve "./notified.json" from "src/routes/+page.server.ts"
file: /Users/hossam/Workspace/wwpray/generator/svelte/src/routes/+page.server.ts
error during build:
RollupError: Could not resolve "./notified.json" from "src/routes/+page.server.ts"
    at error (file:///Users/hossam/Workspace/wwpray/generator/svelte/node_modules/rollup/dist/es/shared/node-entry.js:2287:30)
    at ModuleLoader.handleInvalidResolvedId (file:///Users/hossam/Workspace/wwpray/generator/svelte/node_modules/rollup/dist/es/shared/node-entry.js:24860:24)
    at ModuleLoader.resolveDynamicImport (file:///Users/hossam/Workspace/wwpray/generator/svelte/node_modules/rollup/dist/es/shared/node-entry.js:24920:58)
    at async file:///Users/hossam/Workspace/wwpray/generator/svelte/node_modules/rollup/dist/es/shared/node-entry.js:24807:32
{
    "errorMessage": "Command failed: npm run build",
    "errorType": "Error",
    "stackTrace": [
        "Error: Command failed: npm run build",
        "    at checkExecSyncError (node:child_process:887:11)",
        "    at execSync (node:child_process:959:15)",
        "    at /opt/homebrew/lib/node_modules/serverless/node_modules/cli-progress-footer/lib/private/cli-progress-footer/disable-props.js:87:41",
        "    at handleSubProcessSync (/opt/homebrew/lib/node_modules/serverless/node_modules/cli-progress-footer/lib/private/cli-progress-footer/disable-props.js:33:15)",
        "    at childProcess.execSync (/opt/homebrew/lib/node_modules/serverless/node_modules/cli-progress-footer/lib/private/cli-progress-footer/disable-props.js:86:11)",
        "    at module.exports (/Users/hossam/Workspace/wwpray/generator/generate.js:15:5)",
        "    at module.exports.handler (/Users/hossam/Workspace/wwpray/generator/index.js:65:9)"
    ]
}
```

I run this command to invoke in the generator directory:
`serverless invoke local --function generator`

**Comment by hammady** [comment]
It crashes here: generator/svelte/src/routes/+page.server.ts
