### ISSUE TITLE
Investigate issues in notifier preventing email sending

### ISSUE THREAD

**Issue by hammady** [hammady/wwpray#71]
```
Traceback (most recent call last):
  File "/opt/python/serverless_aws_lambda_sdk/instrument/__init__.py", line 580, in _handler
    result = user_handler(event, context)
  File "/var/task/serverless_sdk/__init__.py", line 144, in wrapped_handler
    return user_handler(event, context)
  File "/var/task/handler.py", line 107, in run
    if validate_topics(new_topics) is False:
  File "/var/task/handler.py", line 90, in validate_topics
    valid_topics = get_valid_topics()
  File "/var/task/handler.py", line 86, in get_valid_topics
    for topic in ses_client.get_contact_list(ContactListName=contact_list_name)["Topics"]
KeyError: 'Topics'
```

Probably related to the deletion of all topics.

**Comment by hammady** [comment]
Closed by 3f6c842f98123fd444625fd91d416969d84604a9. I manually deleted all topics because the code recreates them on demand, but the problem was that on SES, the array "Topics" was completely removed from the response, not just returned as empty array which caused Python `KeyError` to be raised.
