### ISSUE TITLE
Investigate errors in generator

### ISSUE THREAD

**Issue by hammady** [hammady/wwpray#72]
```
ENOENT: no such file or directory, lstat 'svelte'

at lstatSync (node:fs:1668:3)
at statFunc (node:internal/fs/cp/cp-sync:122:15)
at getStatsSync (node:internal/fs/cp/cp-sync:123:19)
at checkPathsSync (node:internal/fs/cp/cp-sync:72:33)
at cpSyncFn (node:internal/fs/cp/cp-sync:58:42)
at Object.cpSync (node:fs:3007:3)
at module.exports (/var/task/generate.js:20:8)
at module.exports.handler (/var/task/index.js:78:9)
```

**Comment by hammady** [comment]
Closed by d669763a60656eb208e67b7d4af115b3fef0f147. This was caused by repeated invocations in notifier due to a bug (solved in #71) causing generator to be triggered repeatedly. The first invocation (cold start) had a fresh file system and passed. Later invocations had file systems with previously generated files causing issues in `cp` when the target is an existing dir.
